export type ScopeItem = {
  id: string
  name: string
  description: string
  category: 'structural' | 'finishes' | 'systems' | 'specialty'
  /** AED per sqft — low end (basic finishes) */
  pricePerSqftMin: number
  /** AED per sqft — high end (premium finishes) */
  pricePerSqftMax: number
  /** Flat-rate fallback for items that don't scale by sqft (AED) */
  flatMin: number
  flatMax: number
  estimatedWeeks: [number, number]
  icon: string // lucide icon name
}

export const SCOPE_CATALOG: ScopeItem[] = [
  // ── Structural ──
  {
    id: 'demolition',
    name: 'Demolition',
    description: 'Stripping existing finishes, removing walls, clearing the space for renovation',
    category: 'structural',
    pricePerSqftMin: 3,
    pricePerSqftMax: 6,
    flatMin: 5000,
    flatMax: 12000,
    estimatedWeeks: [1, 2],
    icon: 'Hammer',
  },
  {
    id: 'extensions',
    name: 'Extension(s)',
    description: 'Structural extensions, room additions, mezzanine floors',
    category: 'structural',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 60000,
    flatMax: 200000,
    estimatedWeeks: [6, 14],
    icon: 'Expand',
  },
  {
    id: 'windows_glazing',
    name: 'Windows / Glazing',
    description: 'Window replacement, double glazing, sliding doors, glass partitions',
    category: 'structural',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 40000,
    estimatedWeeks: [2, 4],
    icon: 'PanelTop',
  },

  // ── Finishes ──
  {
    id: 'kitchen',
    name: 'New kitchen',
    description: 'Cabinets, countertops, backsplash, layout changes',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 30000,
    flatMax: 80000,
    estimatedWeeks: [3, 6],
    icon: 'CookingPot',
  },
  {
    id: 'appliances',
    name: 'Appliances',
    description: 'Kitchen appliances, built-in oven, cooktop, dishwasher, fridge',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 12000,
    flatMax: 50000,
    estimatedWeeks: [1, 2],
    icon: 'Refrigerator',
  },
  {
    id: 'master_bathroom',
    name: 'Master bathroom',
    description: 'Main ensuite, vanity, shower/tub, fixtures, waterproofing, tiling',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 20000,
    flatMax: 50000,
    estimatedWeeks: [2, 4],
    icon: 'Bath',
  },
  {
    id: 'family_bathroom',
    name: 'Family bathroom',
    description: 'Shared family bathroom, vanity, shower/tub, fixtures, tiling',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 15000,
    flatMax: 40000,
    estimatedWeeks: [2, 4],
    icon: 'Bath',
  },
  {
    id: 'ensuite_bathroom',
    name: 'Ensuite bathroom',
    description: 'Secondary ensuite bathroom, vanity, shower, fixtures, tiling',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 12000,
    flatMax: 35000,
    estimatedWeeks: [2, 3],
    icon: 'ShowerHead',
  },
  {
    id: 'powder_room',
    name: 'Powder room',
    description: 'Guest WC, compact vanity, toilet, basin, feature wall',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 8000,
    flatMax: 20000,
    estimatedWeeks: [1, 2],
    icon: 'Droplets',
  },
  {
    id: 'flooring',
    name: 'Flooring & skirting',
    description: 'Tile, marble, wood, vinyl, or engineered flooring and skirting boards',
    category: 'finishes',
    pricePerSqftMin: 10,
    pricePerSqftMax: 30,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Grid3x3',
  },
  {
    id: 'tiling',
    name: 'Tiling',
    description: 'Wall and floor tiling, grouting, pattern layouts, backsplashes',
    category: 'finishes',
    pricePerSqftMin: 6,
    pricePerSqftMax: 20,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'LayoutGrid',
  },
  {
    id: 'paint_walls',
    name: 'Paint & walls',
    description: 'Interior painting, feature walls, wallpaper, wall treatments',
    category: 'finishes',
    pricePerSqftMin: 3,
    pricePerSqftMax: 8,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'PaintBucket',
  },
  {
    id: 'exterior_painting',
    name: 'Exterior villa painting',
    description: 'External wall painting, weatherproofing, facade refresh',
    category: 'finishes',
    pricePerSqftMin: 2,
    pricePerSqftMax: 6,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'PaintRoller',
  },
  {
    id: 'false_ceiling',
    name: 'Ceilings',
    description: 'Gypsum board ceilings, cove lighting channels, bulkheads, drops',
    category: 'finishes',
    pricePerSqftMin: 5,
    pricePerSqftMax: 12,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Layers',
  },
  {
    id: 'wardrobes',
    name: 'Wardrobes',
    description: 'Built-in wardrobes, walk-in closets, custom storage solutions',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 40000,
    estimatedWeeks: [2, 4],
    icon: 'DoorOpen',
  },
  {
    id: 'joinery',
    name: 'Joinery & carpentry',
    description: 'TV units, shelving, custom woodwork, panelling',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 12000,
    flatMax: 50000,
    estimatedWeeks: [2, 5],
    icon: 'Ruler',
  },

  // ── Systems ──
  {
    id: 'electrical',
    name: 'Electrical upgrade',
    description: 'Wiring, outlets, switches, distribution board, lighting points',
    category: 'systems',
    pricePerSqftMin: 4,
    pricePerSqftMax: 10,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Zap',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Water supply, drainage, fixture connections, water heater',
    category: 'systems',
    pricePerSqftMin: 3,
    pricePerSqftMax: 8,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Droplets',
  },
  {
    id: 'hvac',
    name: 'AC upgrade',
    description: 'Air conditioning units, ductwork, thermostat controls',
    category: 'systems',
    pricePerSqftMin: 5,
    pricePerSqftMax: 12,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Wind',
  },
  {
    id: 'lighting',
    name: 'Lighting',
    description: 'Light fixtures, recessed lighting, chandeliers, LED strips, dimmers',
    category: 'specialty',
    pricePerSqftMin: 3,
    pricePerSqftMax: 8,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Lightbulb',
  },

  // ── Specialty ──
  {
    id: 'smart_home',
    name: 'Home automation',
    description: 'Smart lighting, motorized curtains, security systems, smart switches',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 35000,
    estimatedWeeks: [1, 3],
    icon: 'Wifi',
  },
  {
    id: 'home_cinema',
    name: 'Home cinema',
    description: 'Dedicated cinema room, projector, surround sound, acoustic treatment',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 20000,
    flatMax: 70000,
    estimatedWeeks: [2, 4],
    icon: 'Tv',
  },
  {
    id: 'balconies',
    name: 'Balconies',
    description: 'Balcony renovation, flooring, railing, privacy screening',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 5000,
    flatMax: 20000,
    estimatedWeeks: [1, 2],
    icon: 'Fence',
  },
  {
    id: 'garden_terrace',
    name: 'Garden terrace',
    description: 'Terrace design, decking, outdoor furniture area, BBQ setup',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 40000,
    estimatedWeeks: [2, 4],
    icon: 'Flower2',
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    description: 'Garden design, planting, irrigation, pool deck, pergola',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 15000,
    flatMax: 50000,
    estimatedWeeks: [2, 5],
    icon: 'Trees',
  },
]
