export type ScopeItem = {
  id: string
  name: string
  description: string
  category: 'structural' | 'finishes' | 'systems' | 'specialty'
  /** AED per sqft — low end (basic finishes) */
  pricePerSqftMin: number
  /** AED per sqft — high end (premium finishes) */
  pricePerSqftMax: number
  /** Flat-rate fallback for items that don't scale by sqft (AED) */
  flatMin: number
  flatMax: number
  estimatedWeeks: [number, number]
  icon: string // lucide icon name
}

export const SCOPE_CATALOG: ScopeItem[] = [
  {
    id: 'demolition',
    name: 'Demolition',
    description: 'Stripping existing finishes, removing walls, clearing the space for renovation',
    category: 'structural',
    pricePerSqftMin: 3,
    pricePerSqftMax: 8,
    flatMin: 5000,
    flatMax: 15000,
    estimatedWeeks: [1, 2],
    icon: 'Hammer',
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    description: 'Cabinets, countertops, backsplash, appliance fitting, layout changes',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 25000,
    flatMax: 120000,
    estimatedWeeks: [3, 6],
    icon: 'CookingPot',
  },
  {
    id: 'bathrooms',
    name: 'Bathrooms',
    description: 'Vanities, showers, bathtubs, fixtures, waterproofing, tiling',
    category: 'finishes',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 15000,
    flatMax: 60000,
    estimatedWeeks: [2, 5],
    icon: 'Bath',
  },
  {
    id: 'flooring',
    name: 'Flooring',
    description: 'Tile, marble, wood, vinyl, or engineered flooring throughout',
    category: 'finishes',
    pricePerSqftMin: 8,
    pricePerSqftMax: 45,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Grid3x3',
  },
  {
    id: 'paint_walls',
    name: 'Paint & Walls',
    description: 'Interior painting, feature walls, wallpaper, wall treatments',
    category: 'finishes',
    pricePerSqftMin: 3,
    pricePerSqftMax: 12,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'PaintBucket',
  },
  {
    id: 'tiling',
    name: 'Tiling',
    description: 'Wall and floor tiling, grouting, pattern layouts, backsplashes',
    category: 'finishes',
    pricePerSqftMin: 5,
    pricePerSqftMax: 30,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'LayoutGrid',
  },
  {
    id: 'electrical',
    name: 'Electrical',
    description: 'Wiring, outlets, switches, distribution board, lighting points',
    category: 'systems',
    pricePerSqftMin: 4,
    pricePerSqftMax: 15,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Zap',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Water supply, drainage, fixture connections, water heater',
    category: 'systems',
    pricePerSqftMin: 3,
    pricePerSqftMax: 10,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Droplets',
  },
  {
    id: 'hvac',
    name: 'HVAC / AC',
    description: 'Air conditioning units, ductwork, thermostat controls, maintenance',
    category: 'systems',
    pricePerSqftMin: 5,
    pricePerSqftMax: 18,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 3],
    icon: 'Wind',
  },
  {
    id: 'lighting',
    name: 'Lighting',
    description: 'Light fixtures, recessed lighting, chandeliers, LED strips, dimmers',
    category: 'specialty',
    pricePerSqftMin: 2,
    pricePerSqftMax: 12,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Lightbulb',
  },
  {
    id: 'joinery',
    name: 'Joinery & Carpentry',
    description: 'Built-in wardrobes, shelving, TV units, custom woodwork',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 80000,
    estimatedWeeks: [2, 5],
    icon: 'Ruler',
  },
  {
    id: 'false_ceiling',
    name: 'False Ceiling',
    description: 'Gypsum board ceilings, cove lighting channels, bulkheads',
    category: 'specialty',
    pricePerSqftMin: 4,
    pricePerSqftMax: 15,
    flatMin: 0,
    flatMax: 0,
    estimatedWeeks: [1, 2],
    icon: 'Layers',
  },
  {
    id: 'smart_home',
    name: 'Smart Home',
    description: 'Home automation, smart lighting, motorized curtains, security systems',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 8000,
    flatMax: 50000,
    estimatedWeeks: [1, 3],
    icon: 'Wifi',
  },
  {
    id: 'landscaping',
    name: 'Landscaping',
    description: 'Outdoor areas, garden, pool deck, pergola, outdoor kitchen',
    category: 'specialty',
    pricePerSqftMin: 0,
    pricePerSqftMax: 0,
    flatMin: 10000,
    flatMax: 80000,
    estimatedWeeks: [2, 5],
    icon: 'Trees',
  },
]
