'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { ChevronRight, ChevronDown, Plus, Sparkles, Loader2, Trash2 } from 'lucide-react'
import type { Database } from '@/lib/supabase/types'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

type ProjectTask = Database['public']['Tables']['project_tasks']['Row']
type TaskStatus = 'todo' | 'in_progress' | 'done'

type Props = {
  leadId: string
}

const STATUS_CONFIG: Record<TaskStatus, { label: string; bg: string; text: string; dot: string }> = {
  todo: { label: 'To Do', bg: 'bg-zinc-100 dark:bg-zinc-800', text: 'text-zinc-600 dark:text-zinc-400', dot: 'bg-zinc-400' },
  in_progress: { label: 'In Progress', bg: 'bg-amber-50 dark:bg-amber-500/10', text: 'text-amber-700 dark:text-amber-400', dot: 'bg-amber-500' },
  done: { label: 'Done', bg: 'bg-emerald-50 dark:bg-emerald-500/10', text: 'text-emerald-700 dark:text-emerald-400', dot: 'bg-emerald-500' },
}

const COMPLEXITY_COLORS: Record<string, string> = {
  S: 'bg-green-500',
  M: 'bg-amber-500',
  L: 'bg-red-500',
}

export default function TrackerTab({ leadId }: Props) {
  const [tasks, setTasks] = useState<ProjectTask[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [expandedScope, setExpandedScope] = useState<Set<string>>(new Set())
  const [addingSubtask, setAddingSubtask] = useState<string | null>(null)
  const [newSubtaskTitle, setNewSubtaskTitle] = useState('')
  const hasAutoGenerated = useRef(false)

  // Fetch tasks
  const fetchTasks = useCallback(async () => {
    const res = await fetch(`/api/admin/leads/${leadId}/tasks`)
    if (res.ok) {
      const data = await res.json()
      setTasks(data)
      return data as ProjectTask[]
    }
    return []
  }, [leadId])

  // Initial load + auto-generate if empty
  useEffect(() => {
    async function init() {
      const data = await fetchTasks()
      setLoading(false)

      // Auto-generate if no tasks exist and haven't tried yet
      if (data.length === 0 && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true
        await handleGenerate()
      }
    }
    init()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [leadId])

  // Generate tasks via AI
  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const res = await fetch(`/api/admin/leads/${leadId}/tasks/generate`, { method: 'POST' })
      if (res.ok) {
        const data = await res.json()
        setTasks(data)
        // Auto-expand all scope items
        const parentIds = (data as ProjectTask[]).filter(t => !t.parent_id).map(t => t.id)
        setExpandedScope(new Set(parentIds))
      }
    } catch { /* ignore */ }
    setGenerating(false)
  }

  // Update task status
  const handleStatusChange = async (taskId: string, newStatus: TaskStatus) => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t))

    await fetch(`/api/admin/leads/${leadId}/tasks`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ taskId, updates: { status: newStatus } }),
    })
  }

  // Add subtask
  const handleAddSubtask = async (parentId: string) => {
    if (!newSubtaskTitle.trim()) return

    const siblings = tasks.filter(t => t.parent_id === parentId)
    const res = await fetch(`/api/admin/leads/${leadId}/tasks`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        parent_id: parentId,
        title: newSubtaskTitle.trim(),
        sort_order: siblings.length,
        status: 'todo',
      }),
    })

    if (res.ok) {
      const newTask = await res.json()
      setTasks(prev => [...prev, newTask])
      setNewSubtaskTitle('')
      setAddingSubtask(null)
    }
  }

  // Delete task
  const handleDelete = async (taskId: string) => {
    setTasks(prev => prev.filter(t => t.id !== taskId && t.parent_id !== taskId))

    await fetch(`/api/admin/leads/${leadId}/tasks`, {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ taskId }),
    })
  }

  // Toggle scope expand/collapse
  const toggleScope = (scopeId: string) => {
    setExpandedScope(prev => {
      const next = new Set(prev)
      if (next.has(scopeId)) next.delete(scopeId)
      else next.add(scopeId)
      return next
    })
  }

  // Organize tasks
  const parentTasks = tasks.filter(t => !t.parent_id).sort((a, b) => a.sort_order - b.sort_order)
  const getChildren = (parentId: string) => tasks.filter(t => t.parent_id === parentId).sort((a, b) => a.sort_order - b.sort_order)

  // Auto-calculate progress
  const getProgress = (parentId: string) => {
    const children = getChildren(parentId)
    if (children.length === 0) return 0
    const done = children.filter(c => c.status === 'done').length
    return Math.round((done / children.length) * 100)
  }

  const getProgressColor = (pct: number) => {
    if (pct === 100) return 'bg-emerald-500'
    if (pct > 0) return 'bg-amber-500'
    return 'bg-zinc-300 dark:bg-zinc-600'
  }

  // Derive parent status from children
  const getParentStatus = (parentId: string): TaskStatus => {
    const children = getChildren(parentId)
    if (children.length === 0) return 'todo'
    if (children.every(c => c.status === 'done')) return 'done'
    if (children.some(c => c.status === 'in_progress' || c.status === 'done')) return 'in_progress'
    return 'todo'
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (generating) {
    return (
      <div className="flex flex-col items-center justify-center py-16 gap-3">
        <Loader2 className="w-6 h-6 animate-spin text-yellow-500" />
        <p className="text-sm text-muted-foreground">Generating task breakdown...</p>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-6 md:px-8 py-3 border-b bg-white dark:bg-background">
        <div className="text-xs text-muted-foreground">
          {parentTasks.length} scope item{parentTasks.length !== 1 ? 's' : ''} &middot; {tasks.filter(t => t.parent_id).length} tasks
        </div>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleGenerate}
          disabled={generating}
          className="text-xs cursor-pointer gap-1.5"
        >
          <Sparkles className="w-3.5 h-3.5" />
          Regenerate
        </Button>
      </div>

      {/* Scrollable table wrapper */}
      <div className="flex-1 min-h-0 overflow-x-auto overflow-y-auto bg-white dark:bg-background">
        <div className="min-w-[520px]">
      {/* Column headers */}
      <div className="grid grid-cols-[1fr_130px_100px] gap-2 px-6 md:px-8 py-2 text-[11px] uppercase tracking-widest font-medium text-muted-foreground/70 border-b bg-zinc-50/50 dark:bg-zinc-900/30 sticky top-0 z-10">
        <span>Task</span>
        <span>Status</span>
        <span>Progress</span>
      </div>

      {/* Task rows */}
      <div>
        {parentTasks.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 gap-3">
            <p className="text-sm text-muted-foreground">No tasks yet</p>
            <Button onClick={handleGenerate} className="gap-2 cursor-pointer">
              <Sparkles className="w-4 h-4" />
              Generate Tasks
            </Button>
          </div>
        ) : (
          parentTasks.map((parent) => {
            const children = getChildren(parent.id)
            const isOpen = expandedScope.has(parent.id)
            const progress = getProgress(parent.id)
            const parentStatus = getParentStatus(parent.id)
            const statusCfg = STATUS_CONFIG[parentStatus]

            return (
              <div key={parent.id}>
                {/* Parent scope row */}
                <div
                  className="grid grid-cols-[1fr_130px_100px] gap-2 items-center px-6 md:px-8 py-3 hover:bg-muted/30 cursor-pointer border-b transition-colors"
                  onClick={() => toggleScope(parent.id)}
                >
                  <div className="flex items-center gap-2 min-w-0">
                    {isOpen
                      ? <ChevronDown className="w-4 h-4 shrink-0 text-muted-foreground" />
                      : <ChevronRight className="w-4 h-4 shrink-0 text-muted-foreground" />
                    }
                    <span className="font-semibold text-sm truncate">{parent.title}</span>
                    <span className="text-xs text-muted-foreground shrink-0">({children.length})</span>
                  </div>

                  <span className={`inline-flex items-center gap-1.5 text-[11px] font-medium px-2.5 py-1 rounded-full w-fit ${statusCfg.bg} ${statusCfg.text}`}>
                    <span className={`w-1.5 h-1.5 rounded-full ${statusCfg.dot}`} />
                    {statusCfg.label}
                  </span>

                  <div className="flex items-center gap-2">
                    <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-300 ${getProgressColor(progress)}`}
                        style={{ width: `${progress}%` }}
                      />
                    </div>
                    <span className="text-xs text-muted-foreground w-8 text-right">{progress}%</span>
                  </div>
                </div>

                {/* Subtask rows */}
                {isOpen && (
                  <>
                    {children.map((child) => {
                      const childStatus = STATUS_CONFIG[child.status as TaskStatus]
                      return (
                        <div
                          key={child.id}
                          className="grid grid-cols-[1fr_130px_100px] gap-2 items-center pl-12 pr-6 md:pl-14 md:pr-8 py-2.5 hover:bg-muted/20 border-b border-dashed transition-colors group"
                        >
                          <div className="flex items-center gap-2.5 min-w-0">
                            <span className={`w-2 h-2 rounded-full shrink-0 ${childStatus.dot}`} />
                            <span className="text-sm truncate">{child.title}</span>
                            {child.complexity && (
                              <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded text-white shrink-0 ${COMPLEXITY_COLORS[child.complexity] ?? 'bg-zinc-400'}`}>
                                {child.complexity}
                              </span>
                            )}
                          </div>

                          <Select value={child.status} onValueChange={(v) => handleStatusChange(child.id, v as TaskStatus)}>
                            <SelectTrigger className="h-7 text-[11px] border-0 shadow-none px-0 w-fit gap-1.5 cursor-pointer [&>svg:last-child]:hidden">
                              <span className={`inline-flex items-center gap-1.5 font-medium px-2.5 py-0.5 rounded-full ${childStatus.bg} ${childStatus.text}`}>
                                <span className={`w-1.5 h-1.5 rounded-full ${childStatus.dot}`} />
                                {childStatus.label}
                              </span>
                            </SelectTrigger>
                            <SelectContent>
                              {Object.entries(STATUS_CONFIG).map(([key, cfg]) => (
                                <SelectItem key={key} value={key} className="text-xs">
                                  <span className="flex items-center gap-2">
                                    <span className={`w-1.5 h-1.5 rounded-full ${cfg.dot}`} />
                                    {cfg.label}
                                  </span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>

                          <div className="flex justify-end">
                            <button
                              onClick={() => handleDelete(child.id)}
                              className="opacity-0 group-hover:opacity-100 transition-opacity text-muted-foreground hover:text-destructive cursor-pointer p-1"
                              title="Delete task"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>
                      )
                    })}

                    {/* Add subtask */}
                    {addingSubtask === parent.id ? (
                      <div className="flex items-center gap-2 pl-12 pr-6 md:pl-14 md:pr-8 py-2 border-b">
                        <input
                          value={newSubtaskTitle}
                          onChange={(e) => setNewSubtaskTitle(e.target.value)}
                          placeholder="New task title..."
                          className="flex-1 text-sm bg-transparent outline-none placeholder:text-muted-foreground/40"
                          autoFocus
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') handleAddSubtask(parent.id)
                            if (e.key === 'Escape') { setAddingSubtask(null); setNewSubtaskTitle('') }
                          }}
                        />
                        <Button size="sm" variant="ghost" onClick={() => handleAddSubtask(parent.id)} className="text-xs cursor-pointer h-7">
                          Add
                        </Button>
                        <Button size="sm" variant="ghost" onClick={() => { setAddingSubtask(null); setNewSubtaskTitle('') }} className="text-xs cursor-pointer h-7">
                          Cancel
                        </Button>
                      </div>
                    ) : (
                      <button
                        onClick={() => setAddingSubtask(parent.id)}
                        className="flex items-center gap-1.5 pl-12 md:pl-14 py-2 text-xs text-muted-foreground hover:text-foreground transition-colors cursor-pointer border-b"
                      >
                        <Plus className="w-3.5 h-3.5" />
                        Add subtask
                      </button>
                    )}
                  </>
                )}
              </div>
            )
          })
        )}
      </div>
        </div>{/* end min-w wrapper */}
      </div>{/* end scrollable wrapper */}
    </div>
  )
}
